### ISSUE TITLE
Fails to build on Mac OS X: myexception.hpp:31:43: error: expected class name

### ISSUE THREAD

**Issue by LudovicRousseau** [islog/liblogicalaccess#23]
Hello,

If I compile on Mountain Lion (10.8) I get the error:

```
liblogicalaccess/include/logicalaccess/myexception.hpp:31:43: error: expected class name
    class bad_function_call : public std::bad_function_call
                                          ^
```

I am using:

```
$ g++ --version
i686-apple-darwin11-llvm-g++-4.2 (GCC) 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2336.11.00)
```
